### PR TITLE
Enhancement: Replace concrete class with an anonymous class

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] replaces `TupleIterator` with an anonymous class

💁‍♂️ For reference, see [my suggestion to your question on Reddit](https://www.reddit.com/r/PHP/comments/8m9fxj/what_about_two_classes_in_one_file/dzlsp19/).

### CODE REVIEW

**Comment by localheinz** [comment]
@brendt 

Makes a lot of sense, amended!

**Comment by brendt** [comment]
I'm going to merge this, though later today. I linked to the old code on Reddit and Twitter, and would like others to still give their opinion, but I'm 100% for this solution!

**Comment by brendt** [comment]
Merged, thanks Andreas!

**Comment by localheinz** [comment]
Thank you, @brendt!

**Pull request merged**
